name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]
        wordpress-version: [latest, 6.4, 6.5]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, zip, gd, curl, mysql
        coverage: xdebug
    
    - name: Setup WordPress test environment
      run: |
        bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost ${{ matrix.wordpress-version }}
    
    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
    
    - name: Run unit tests
      run: |
        composer test-unit
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/
    
    - name: Run integration tests
      run: |
        composer test-integration
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/
    
    - name: Run smoke tests
      run: |
        composer test-smoke
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/
    
    - name: Generate coverage report
      run: |
        composer test-coverage
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: tests/coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
